appName: aks-helloworld
namespace: sampleapp
imagesB:
  tag: 46e4f85
imagesA:
  tag: b30e4eb
imagesC:
  tag: 46e4f85
imagesK:
  tag: 46e4f85
imagesF:
  tag: 46e4f85
imagesT:
  tag: 46e4f85
imagesS:
  tag: 46e4f85
imagesL:
  tag: 46e4f85
imagesQ:
  tag: 46e4f85
imagesR:
  tag: 46e4f85
imagesJ:
  tag: 0f07129
imagesE:
  tag: 0f07129
imagesP:
  tag: 0f07129
imagesN:
  tag: 0f07129
imagesO:
  tag: 0f07129
imagesI:
  tag: 46e4f85
imagesG:
  tag: 0f07129
imagesM:
  tag: 0f07129
imagesD:
  tag: 0f07129
imagesH:
  tag: 0f07129
