appName: aks-helloworld
namespace: sampleapp
imagesB:
  tag: 0f07129
imagesA:
  tag: 0f07129
imagesC:
  tag: 0f07129
imagesK:
  tag: 76da709
imagesF:
  tag: 0f07129
imagesT:
  tag: 0f07129
imagesS:
  tag: 0f07129
imagesL:
  tag: 0f07129
imagesQ:
  tag: 0f07129
imagesR:
  tag: 0f07129
imagesJ:
  tag: 0f07129
imagesE:
  tag: 0f07129
imagesP:
  tag: 0f07129
imagesN:
  tag: 0f07129
imagesO:
  tag: 0f07129
imagesI:
  tag: 0f07129
imagesG:
  tag: 0f07129
imagesM:
  tag: 0f07129
imagesD:
  tag: 0f07129
imagesH:
  tag: 0f07129
