appName: aks-helloworld
namespace: sampleapp
imagesB:
  tag: 182ca72
imagesA:
  tag: 390afcb
imagesC:
  tag: 182ca72
imagesK:
  tag: 182ca72
imagesF:
  tag: 182ca72
imagesT:
  tag: 9fa6654
imagesS:
  tag: 55c8212
imagesL:
  tag: 9fa6654
imagesQ:
  tag: 182ca72
imagesR:
  tag: 9fa6654
